version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/code/Backend
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/code/Backend
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ubuntu