DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS INTERESTS;
DROP TABLE IF EXISTS RECRUITMENT;
DROP TABLE IF EXISTS RECRUITMENT_INTEREST;

CREATE TABLE USERS (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    DETAILS CLOB,
    EMAIL VARCHAR(255),
    LOCATION_LATITUDE DECIMAL(18,10),
    LOCATION_LONGITUDE DECIMAL(18,10),
    NAME VARCHAR(255),
    NICKNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    POPULARITY_COUNT INTEGER,
    POPULARITY_RATE FLOAT(53),
    POPULARITY_TOTAL FLOAT(53),
    REFRESH_TOKEN VARCHAR(255),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE INTERESTS (
    INTERESTS_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    USER_ID BIGINT,
    PRIMARY KEY (INTERESTS_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE RECRUITMENT (
    RECRUIMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
    CATEGORY VARCHAR(255),
    CONTENT CLOB,
    TITLE VARCHAR(255),
    STATUS VARCHAR(255),
    USER_ID BIGINT,
    PRIMARY KEY (RECRUIMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE RECRUITMENT_INTEREST (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    RECRUITMENT_ID BIGINT,
    USER_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (RECRUITMENT_ID) REFERENCES RECRUITMENT (RECRUIMENT_ID)
);